# Generated by Django 5.0.6 on 2024-07-02 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_profile_bio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='is_student',
            new_name='is_passenger',
        ),
    ]
