# Generated by Django 5.0.6 on 2024-07-02 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_route'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
