# Generated by Django 5.0.6 on 2024-07-03 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_bookings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='route',
            old_name='destination_lat',
            new_name='dropoff_lat',
        ),
        migrations.RenameField(
            model_name='route',
            old_name='destination_lng',
            new_name='dropoff_lng',
        ),
        migrations.RenameField(
            model_name='route',
            old_name='origin_lat',
            new_name='pickup_lat',
        ),
        migrations.RenameField(
            model_name='route',
            old_name='origin_lng',
            new_name='pickup_lng',
        ),
        migrations.RemoveField(
            model_name='route',
            name='distance_meters',
        ),
        migrations.RemoveField(
            model_name='route',
            name='polyline',
        ),
        migrations.AddField(
            model_name='bookings',
            name='distance',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bookings',
            name='dropoff_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bookings',
            name='duration',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bookings',
            name='pickup_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='distance',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='dropoff_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='pickup_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='duration',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
