# Generated by Django 5.0.6 on 2024-07-04 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_rename_bookings_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='profile',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='core.profile'),
            preserve_default=False,
        ),
    ]
