# Generated by Django 5.0.6 on 2024-07-04 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_prebooking_delete_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prebooking',
            name='distance',
        ),
        migrations.RemoveField(
            model_name='prebooking',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='route',
            name='distance',
        ),
        migrations.RemoveField(
            model_name='route',
            name='duration',
        ),
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(max_length=30),
        ),
    ]
