# Generated by Django 5.0.6 on 2024-07-05 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_prebooking_created_at_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_id',
            field=models.CharField(default='', max_length=6, unique=True),
            preserve_default=False,
        ),
    ]
