# Generated by Django 5.0.6 on 2024-07-05 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_booking_booking_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_id',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
