# Generated by Django 5.0.6 on 2024-07-05 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_webhookevent_booking_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WebhookEvent',
        ),
    ]
