# Generated by Django 5.0.6 on 2024-07-05 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_delete_webhookevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='prebooking',
            name='session_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
