# Generated by Django 5.0.6 on 2024-07-06 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_prebooking_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='session_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
