# Generated by Django 5.0.6 on 2024-07-06 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_booking_amount_paid_booking_payment_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='amount_paid',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='payment_id',
        ),
        migrations.AddField(
            model_name='booking',
            name='driver',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_as_driver', to='core.profile'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='dropoff_location',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='pickup_location',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='booking_as_passenger', to='core.profile'),
        ),
        migrations.AlterField(
            model_name='prebooking',
            name='dropoff_location',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='prebooking',
            name='pickup_location',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='route',
            name='dropoff_location',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='route',
            name='pickup_location',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
