# Generated by Django 5.0.6 on 2024-07-06 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_remove_booking_amount_paid_remove_booking_payment_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='driver',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_as_driver', to='core.profile'),
        ),
    ]
