# Generated by Django 5.0.6 on 2024-07-06 12:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_booking_driver'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passenger',
            name='user',
        ),
        migrations.AlterField(
            model_name='profile',
            name='TODA',
            field=models.CharField(blank=True, choices=[('Loyola Heights (White)', 'Loyola Heights (White)'), ('Loyola Pansol (Green)', 'Loyola Pansol (Green)')], max_length=22),
        ),
        migrations.CreateModel(
            name='PastBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.CharField(max_length=10, unique=True)),
                ('pickup_location', models.CharField(max_length=255)),
                ('dropoff_location', models.CharField(max_length=255)),
                ('pickup_lat', models.FloatField()),
                ('pickup_lng', models.FloatField()),
                ('dropoff_lat', models.FloatField()),
                ('dropoff_lng', models.FloatField()),
                ('status', models.CharField(max_length=10)),
                ('payment_method', models.CharField(max_length=10)),
                ('driver_rating', models.FloatField(blank=True)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('driver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='past_booking_as_driver', to='core.profile')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='past_booking_as_passenger', to='core.profile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Driver',
        ),
        migrations.DeleteModel(
            name='Passenger',
        ),
    ]
