# Generated by Django 5.0.6 on 2024-07-06 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_remove_passenger_user_alter_profile_toda_pastbooking_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pastbooking',
            old_name='driver_rating',
            new_name='rating',
        ),
    ]
