# Generated by Django 5.0.6 on 2024-07-06 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_rename_driver_rating_pastbooking_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pastbooking',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pastbooking',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
