# Generated by Django 5.0.6 on 2024-07-07 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_pasttrip_delete_pastbooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='pasttrip',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
