# Generated by Django 5.0.6 on 2024-07-07 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_pasttrip_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='distance',
            field=models.CharField(default='', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='estimated_duration',
            field=models.CharField(default='', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pasttrip',
            name='distance',
            field=models.CharField(default='', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prebooking',
            name='distance',
            field=models.CharField(default='', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prebooking',
            name='estimated_duration',
            field=models.CharField(default='', max_length=5),
            preserve_default=False,
        ),
    ]
