# Generated by Django 5.0.6 on 2024-07-07 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_booking_distance_booking_estimated_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='fare_amount',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pasttrip',
            name='fare_amount',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prebooking',
            name='fare_amount',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
