# Generated by Django 5.0.6 on 2024-07-07 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_booking_fare_amount_pasttrip_fare_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prebooking',
            name='distance_value',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='prebooking',
            name='fare_amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
