# Generated by Django 5.0.6 on 2024-07-07 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_prebooking_distance_value_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FareMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_fare', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('base_distance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('fare_per_km', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.AlterField(
            model_name='booking',
            name='fare_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pasttrip',
            name='fare_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='prebooking',
            name='fare_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
