# Generated by Django 5.0.6 on 2024-07-07 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_farematrix_alter_booking_fare_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prebooking',
            name='distance_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
