# Generated by Django 5.0.6 on 2024-07-07 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_alter_prebooking_distance_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prebooking',
            name='distance_value',
        ),
        migrations.AddField(
            model_name='route',
            name='distance',
            field=models.CharField(default='', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='route',
            name='distance_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='route',
            name='estimated_duration',
            field=models.CharField(default='', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='route',
            name='fare_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='prebooking',
            name='fare_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
