# Generated by Django 5.0.6 on 2024-07-08 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_remove_prebooking_distance_value_route_distance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pasttrip',
            name='comment',
            field=models.TextField(blank=True, default=''),
        ),
    ]
