# Generated by Django 5.0.6 on 2024-07-08 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_alter_pasttrip_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='distance_value',
        ),
    ]
