# Generated by Django 5.0.6 on 2024-07-08 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_remove_route_distance_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='fare_amount',
            new_name='fare',
        ),
        migrations.RenameField(
            model_name='pasttrip',
            old_name='fare_amount',
            new_name='fare',
        ),
        migrations.RenameField(
            model_name='prebooking',
            old_name='fare_amount',
            new_name='fare',
        ),
        migrations.RenameField(
            model_name='route',
            old_name='fare_amount',
            new_name='fare',
        ),
    ]
