# Generated by Django 5.0.6 on 2024-07-11 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_rename_fare_amount_booking_fare_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='default_profile.png', upload_to='profile_pictures/'),
        ),
    ]
