# Generated by Django 5.0.6 on 2024-07-16 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_profile_signup_confirmation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='signup_confirmation',
        ),
    ]
