# Generated by Django 5.0.6 on 2024-07-16 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_remove_profile_signup_confirmation'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='additional_distance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
