# Generated by Django 5.0.6 on 2024-07-17 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_route_additional_distance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='additional_distance',
            field=models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=10, null=True),
        ),
    ]
