# Generated by Django 5.0.6 on 2024-07-18 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_alter_route_additional_distance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='profile_pictures/default_profile.png', upload_to='profile_pictures/'),
        ),
    ]
