# Generated by Django 4.2.13 on 2024-07-19 21:07

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_alter_booking_created_at_alter_pasttrip_completed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(default='profile_pictures/default_profile.png', max_length=255, verbose_name='profile_picture'),
        ),
    ]
