# Generated by Django 4.2.13 on 2024-07-20 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pasttrip',
            name='distance',
            field=models.CharField(max_length=10),
        ),
    ]
